os: linux

dist: focal

language: dart

dart:
  - dev

dart_task:
  - dartfmt: true

cache:
  directories:
    - $HOME/.pub-cache

branches:
  only:
    - master

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN
