name: wordpress_api
description: A WordPress API client for dart with support for WooCommerce and custom namespaces.
version: 0.1.3+1
homepage: https://github.com/dhmgroup/dart-wp

environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'

dependencies:
  http: ^0.12.0+4
