name: wordpress_api
description: A WordPress REST API client for dart with support for WooCommerce and custom namespaces.
version: 0.2.0
homepage: https://github.com/dhmgroup/dart-wp

environment:
    sdk: ">=2.6.0 <3.0.0"

dependencies:
    dio: ^3.0.9
    json_annotation: ^3.0.1
    logger: ^0.9.1
    meta: ^1.1.8

dev_dependencies:
    build_runner: ^1.10.0
    json_serializable: ^3.3.0
    lint: ^1.2.0
